### ISSUE TITLE
add link to GitHub on npm

### ISSUE THREAD

**Issue by thealexbaron** [mooz/node-pdf-image#4]
Hello,

I almost didn't get to add my contributions to this project because I couldn't find the GitHub repo. Please add a link to npm to ensure that this doesn't happen to other devs who want to contribute.

**Comment by rbecheras** [comment]
Yes, your right I've notice that however the package.json contains:

    "repository": {
      "type": "git",
      "url": "https://github.com/mooz/node-pdf-image.git"
    },

I had the same issue with another personal module [autostatic-server](https://www.npmjs.com/package/autostatic-server)

I also got this field in package.json

  "repository": {
    "type": "git",
    "url": "https://github.com/rbecheras/node-autostatic-server.git"
  },

To fix it, I added theses fields:

  "bugs": {
    "url": "https://github.com/rbecheras/node-autostatic-server/issues"
  },
  "homepage": "https://github.com/rbecheras/node-autostatic-server#readme",

I don't know what specific field fixed the issue, but why not adding all of them ?

So I added it and bumped the package version to 1.0.1.

> I created a new tag v1.0.1 in my fork, and I will create a pull request for integrating my commits in upstream, but @mooz , don't forget to create the tag yourself because tags don't come with pull requests.
> Then to update the npm public registry, you have to `npm publish` again, after the git tag will be created

**Comment by rbecheras** [comment]
- I created [a new pull request](
https://github.com/mooz/node-pdf-image/pull/5)  for integrating my commits in upstream
-  I also created [a new tag v1.0.1 in my fork](https://github.com/rbecheras/node-pdf-image/releases)
- @mooz , don't forget to create the tag yourself because tags don't come with pull requests.
- Then to update the npm public registry, you have to `npm publish` again, after the git tag will be created
